spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true # Eureka에 등록된 서비스 이름으로 라우팅 활성화


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: \
        http://be12-team1:nhnacademy123!@127.0.0.1:10419/eureka/,\
        http://be12-team1:nhnacademy123!@127.0.0.1:10420/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: health, info