# Gateway Service의 로컬 설정 파일
server:
  port: ${SERVER_PORT} # 포트는 실행 시 환경 변수로 주입

  # Config Server 연결을 위한 최소한의 설정


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_URL}

spring:
  config:
    import: configserver:http://config-server:10418
  cloud:
    config:
      username: be12-team1
      password: nhnacademy123!
  application:
    name: gateway