server:
  port: 10400
#  forward-headers-strategy: framework
#  ssl:
#    enabled: true
#    key-store: classpath:bootsecurity.p12
#    key-store-password: ${SSL_PW} #trillion-book
#    key-store-type: PKCS12
#    key-alias: bootsecurity

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
    config:
      enabled: false
### 유레카 서버 등록 필요없으면 아래 해제하세요 + appliction.yml 전체주석
#eureka:
#  client:
#    enabled: false

#uri:
#  service:
#    auth: http://localhost:10401
#    member: http://localhost:10403
#    book: http://localhost:10413
#    order: http://localhost:10407
#    coupon: http://localhost:10409
#    search: http://localhost:10410

logging:
  level:
    com.nhnacademy.gateway.GatewayApplication: DEBUG
